spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234560.0
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-forum # ???
  output:
    ansi:
      enabled: ALWAYS # ?????????
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:xml/**/*.xml
#      map-underscore-to-camel-case: true

server:
  port: 8080 # ?????

# ????
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    root: info # ??????
    com.example.springforum: debug # ????????
  file:
    path: D:/project/forum # ??????

forum:
  default:
    topBoardNum: 9