spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_test?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234560.0
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    configuration: # ???? MyBatis??
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true #????????
  application:
    name: spring-forum # ???
  output:
    ansi:
      enabled: ALWAYS # ?????????

# ?????
server:
  port: 8080 # ?????

# ????
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    root: info # ??????
    com.example.springforum: debug # ????????
  file:
    path: D:/project/forum # ??????

